#Pig is a game where you can have between 2 to 4 players. The object is to roll the dice each turn and add up your score to 50. The first
#to reach 50 wins. You may roll as many times as you like each turn. HOWEVER, if you roll a 1, your turn ends and you do not get points
#from that turn. You must decide how much you want to roll each turn, as the more you roll the greater chances you have of getting a 1.
#Points from previous turns where a 1 was not rolled are kept.

#Tasks
#allow user to roll the a dice. Need a random generator to give us a number between 1 - 6
#Ask how many players are joining and create placeholders for their scores, with a threshold of 50 set
#Game needs to be able to go through each player and give them a turn. Should specifiy whos turn it is.
#We then to need to ask the user if they want to continue to roll the dice. Need a yes or no option, if yes, roll again.
#Need to end the turn if rolled a 1 and set points for that turn to 0
#Turn score needs to be able to compound roll values
#When they stop their turn we need the score to go to their final score
#Have a limit on the final score of 50. If someone reaches 50, they win and game is ended.

import random #importing random, a module in Python's standard library. The random module provides tools for generating random numbers, choosing random items, and more.

def roll(): #creating a random roll function
    min_value = 1 #input min number the dice will have
    max_value = 6 #input max number the dice will have 
    roll = random.randint(min_value, max_value) #.randint is a function inside the random module. It stands for "random integer." Randint comes after random because it is a function inside random module.
    return roll #signifies the function to return the value of the roll object

while True: # a while true loop creates an infinite loop that continues to ask the player for # of players, until number given is valid.
    players = input('Enter the number of players (2 - 4): ') #defining players, using input function that will intake a string reponse. Giving an initial message by already entering something in the input brackets
    if players.isdigit(): #Checks if the input is a valid whole number. If the user enters "abc" or "2.5", this evaluates to False. Goes to 'Invalid'
        players = int(players) #if players is a whole number, int() will convert the string input into a integer
        if 2 <= players <=4: #Checks if the number of players is between 2 and 4 (inclusive).
            break #breaks the infinte while true loop. This happens only if the input passes all validation checks.
        else:
            print('Must be between 2 - 4 players') #If the input is a number (due to isdigit() returning True) but is not between 2 and 4, this message is printed.
    else: print('Invalid, try again.') #If players.isdigit() is False (meaning the input was not a number), this error message is printed.     
        
print(players) #After the loop is exited (because valid input was provided), the program prints the valid number of players.      

max_score = 50  #setting the max score of 50, once this score is reached the game will end.
player_scores = [0 for i in range(players)] #creates a list and initializes it with zeros, one for each player. It will eventually hold the scores for all players.
#The range() function generates a sequence of numbers starting from 0 up to (but not including) the value of players. For example, if players = 3, range(players) produces 0, 1, 2.
#for i in range(players): A loop is run for each number in the sequence generated by range(players). For each iteration of the loop, the number 0 is added to the list.
print(player_scores) #prints players scores. Should be a list with a 0 for each player.

while max(player_scores) < max_score: #creating a while loop that continues as long as player scores are under 50. 
    for player_idx in range(players): #this will go through each 0 in the list we created and give every player a turn. This ensures each player in the last turn gets to try even if someone reached 50.
        print('\nPlayer number', player_idx + 1, 'turn has just started!\n') #prints the message that the players turn has started. \n in front puts a blank line above, and \n at the end created a blank line below, this give more readability. Adding 1 to the index because it satrts at 0.
        print('Your total score is:', player_scores[player_idx],'\n') #print another message with the players score. The score is indexed within the list of scores we created in the player_scores object. Pay attention to the quotation marks.
        current_score = 0 #sets the current score to 0 each turn. That way its a fresh slate for each turn.
        
        while True: #creating another infinite loop for playing the actual game.
            should_roll = input('would you like to roll (y)?') #requiring input if the player would like to roll the dice. The player can roll as much as they want.
            if should_roll.lower() != 'y': #setting the needed response to roll. By putting 'if should_roll does NOT equal y', it ensures only yes will move forward.They can input Y and .lower will change it to y. Anything else is considered no.
                break #if the player does not press y for yes, it ends their turn.
            else: #if y is entered the code moves forward into the game
                value = roll() #the roll function we created eariler will be set to the value object. Meaning the roll function will execute and save the result into the object.
                if value == 1: #setting the rule that if you roll a 1, you turn ends, and you do not keep any points for this turn.
                    print('You rolled a 1! Turn done!') #if value equals 1 this message will print to the player
                    current_score = 0 #this sets their turn score to 0 no matter how many successful rolls they had prior in this turn.
                    break #ends the while true loop, and loops back into the while max loop for the next player
                else:
                    current_score += value #if anything other than a 1 is rolled the score is added into current_score with += allowing the numbers to stack with each turn.
                    print('You rolled a: ', value) #this prints a message letting the player know what they have rolled showing the value object for each roll.
                    
                print('Your score is:', current_score) #this prints a message letting the player know their turn score, then loops back to the begin on the while True loop. As the current_score object is compounded, it will update with each roll.
                
        player_scores[player_idx] += current_score #after the While True loop breaks either from a 1 or ending their turn, the current_score is added into our player_score list in the index of that player. If they rolled a 1, the current_score of 0 is added.
        print('Your total score is:', player_scores[player_idx]) #prints a message to give them their total score, pulling from the player_scores list, indexed for that player.


highest_score = max(player_scores) #after the while max loop has broke(50 is reached), this code is then executed. We locate the max score in the player_score list and set it to the object highest_score
winning_idx = player_scores.index(highest_score) #we then index which player the highest score belongs to.
print('player number', winning_idx + 1, 'is the winner with a score of:', highest_score) #lastly print a winning message that shows the winning index + 1 (because the index starts at 0) and the highest score.
























